# Generated by Django 2.1.1 on 2018-11-05 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('minimum_term', models.CharField(max_length=250)),
                ('connection_typ', models.CharField(choices=[('K', 'Cable'), ('D', 'DSL'), ('S', 'Satellite'), ('G', 'Glass Fibre'), ('L', 'LTE/UMTS'), ('W', 'WiMAX')], max_length=1)),
                ('renewal', models.CharField(max_length=250)),
                ('throttling', models.CharField(max_length=250)),
                ('throttling_rate', models.CharField(max_length=250)),
                ('desired_schedule', models.CharField(max_length=250)),
                ('provider_information', models.CharField(max_length=250)),
                ('email_mailboxes', models.CharField(max_length=250)),
                ('advise', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneToll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_id', models.ForeignKey(on_delete=None, to='Prototype_0_1.Advantage', verbose_name='advantage id')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=1)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prototype_0_1.Contract', verbose_name='contract id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='RemainingTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prototype_0_1.Contract', verbose_name='contract id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='phone_toll_id',
            field=models.ForeignKey(on_delete=None, to='Prototype_0_1.PhoneToll', verbose_name='phone toll id'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price_id',
            field=models.ForeignKey(on_delete=None, to='Prototype_0_1.Price', verbose_name='price id'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prototype_0_1.Provider', verbose_name='provider id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prototype_0_1.Rating', verbose_name='rating id'),
        ),
    ]
