# Generated by Django 2.1.1 on 2018-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prototype_0_1', '0002_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
